### ISSUE TITLE
Incorrect path for ssh_host_*_key in sshd_config: can't login by ssh into my box

### ISSUE THREAD

**Issue by alrf** [chef-cookbooks/openssh#102]
### Cookbook version
v2.4.0

### Chef-client version
12.7.2

### Platform Details
CentOS 6.6

### Scenario:
include_recipe 'openssh::default' in my own recipe

### Steps to Reproduce:
include_recipe 'openssh::default'

### Expected Result:
[What are you expecting to happen as the consequence of above reproduction steps?]

### Actual Result:
https://github.com/chef-cookbooks/openssh/blob/master/attributes/default.rb#L91
Why are you using '/var/ssh' path (instead of '/etc/ssh')?
I'm getting the error 'file not found' when I type the commands:
file /var/ssh/ssh_host_rsa_key
or 
file /var/ssh/ssh_host_dsa_key

I can't login in my box by this reason:
'Read from socket failed: Connection reset by peer'

**Comment by alrf** [comment]
Fix for this issue:
default['openssh']['server']['host_key'] = ['/etc/ssh/ssh_host_rsa_key', '/etc/ssh/ssh_host_dsa_key']

**Comment by bcg62** [comment]
Also seeing this, cased by this commit. https://github.com/chef-cookbooks/openssh/commit/34887f9e0d0a53ef683213c3e5e2a72d222b8718

/etc/init.d/sshd on rhel/centos < 7 sets the key locations to:

```
RSA1_KEY=/etc/ssh/ssh_host_key
RSA_KEY=/etc/ssh/ssh_host_rsa_key
DSA_KEY=/etc/ssh/ssh_host_dsa_key
```

**Comment by lucymhdavies** [comment]
We noticed this too this morning.

PR: https://github.com/chef-cookbooks/openssh/pull/103

**Comment by tas50** [comment]
This is fixed on master and I'll get a release out asap
