### ISSUE TITLE
 Bad configuration option: RevokedKeys

### ISSUE THREAD

**Issue by bcg62** [chef-cookbooks/openssh#111]
### Cookbook version
[Version of the cookbook where you are encountering the issue]
2.6.0

### Chef-client version
[Version of chef-client in your environment]
12.19.36

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]
centos 5.11 x86_64

### Scenario:
[What you are trying to achieve and you can't?]
cant start sshd

### Steps to Reproduce:
install on centos 5.11

### Expected Result:
start sshd

### Actual Result:
Starting sshd: /etc/ssh/sshd_config: line 29: Bad configuration option: RevokedKeys
/etc/ssh/sshd_config: terminating, 1 bad configuration options

**Comment by tas50** [comment]
@bcg62 Thanks for the report, but since CentOS 5 is EOL we no longer support that version. Logic that previously supported CentOS 5 has been removed. You may have luck with an older version of the cookbook developed when CentOS 5 was still a supported distro by the CentOS project.

**Comment by bcg62** [comment]
@tas50 then at the very least the cookbook should refuse to run. Anyone who uses it in the current state is going to wind up with a node where ssh cannot start and it is now inaccessible

**Comment by bcg62** [comment]
For anyone else who discovers this issue, you can do the following in a wrapper cookbook.

```
case node['platform_family']
when 'rhel'
  if node['platform_version'].to_i < 6
    rm_default('openssh', 'server', 'trusted_user_c_a_keys')
    rm_default('openssh', 'server', 'revoked_keys')
  end
end
```

**Comment by jblaine** [comment]
RHEL 5.x is still supported under extended support contracts and is affected by this as well :(

Thank you for workaround, @bcg62

**Comment by jblaine** [comment]
As a note - There is no mention in `CHANGELOG.md` of support for "EL" less than 6 being removed from the cookbook at any point in time. That's a bummer, especially with no major version bump for the cookbook.
