### ISSUE TITLE
sshd -t validation failure leaves the invalid configuration in place

### ISSUE THREAD

**Issue by msgarbossa** [chef-cookbooks/openssh#118]
### Cookbook version
2.7.0

### Chef-client version
14.2.0 and earlier

### Platform Details
RHEL 7.5, 6.9, AIX 7.1

### Scenario:
When the SSH configurations fails to validate using /usr/sbin/sshd -t, the bad configuration file is left in /etc/ssh/sshd_config after raising an exception.  When running chef-client at regular intervals, the subsequent chef-client runs complete successfully even though the configuration is invalid.  If the server were to reboot, the sshd process would not come up.  This behavior defeats the purpose of the sshd -t test.  I think a better solution would be to use /usr/sbin/sshd -t -f <desired_config_file> or else restore the backup of the previous config file when the validation fails.  

### Steps to Reproduce:
Set an invalid attribute to generate an invalid configuration file:
```
"openssh": {
  "server": {
    "invalid_attribute": true
  }
}
```

### Expected Result:
/usr/sbin/sshd -t test fails and original /etc/ssh/sshd_config file is preserved to avoid problems with SSH if the server were to reboot.

### Actual Result:
The bad attribute is still written to the configuration file, leaving an invalid configuration on the server.
```
[root@dokken /]# grep InvalidAttribute /etc/ssh/sshd_config
InvalidAttribute true
```
Subsequent chef-client runs succeed because the configuration doesn't need to be updated, even though the configuration is invalid.

**Comment by msgarbossa** [comment]
A possible solution to prevent a bad configuration from being saved would be to write the new configuration to a temporary file and then run `/usr/sbin/sshd -t -f /tmp/sshd_config.new` against it.  I can think of a few ways this could be implemented.  The key is to do the validation **before** updating /etc/ssh/sshd_config.  Otherwise the high level process would be an automated backout, which I think has more risk and would result in extra converges on every chef-client run.

1. Use the Template Mixin to render the template in memory and compare to the current config file to determine if a change is needed.  This would probably work better in a custom resource.
```
contents_desired = Chef::Mixin::Template::TemplateContext.new(variables).render_template(template_file)
contents_current = ::File.read(ntp_conf)
if contents_current != contents_desired
  ... stage temp config, validate, mv to /etc/ssh/sshd_config after validated
end
```

2. Replace the sshd-config-check execute resource with a subscribes/before ruby block to run before the template file makes a change.  The ruby block would need to render the temporary template file and validate it.  If the validation fails, the easy way to prevent the file from being saved would be to stop execution and raise an exception.
```
ruby_block 'validate-sshd_config' do
  block do
    ... write template out to temp file
    ... run /usr/sbin/sshd -t -f /tmp/sshd_config.new to validate
    ... raise exception if non-zero return code
  end
  action :nothing
  subscribes :run, 'template[/etc/ssh/sshd_config]', :before
end
```

It might take some combination.  The Mixin::Template would be cleaner in a custom resource, which would add a lot of flexibility (optionally raise exception if validation fails or print a warning and skip making the change).  Perhaps the subscribes/before resource could be another template resource that writes the temp file and does an immediate notification to a validation execute resource similar to the current one.

**Comment by tas50** [comment]
This is some pretty legacy based code that I think we can easily cleanup. In the later Chef 12 releases we added the ability to verify content *before* templating out files. I'm traveling today, but I'll see if I can get this wired up. It's a much better way to wire up this functionality and works on all supported Chef releases.
