### ISSUE TITLE
The iptables cookbook bump to 7.0.0 breaks compat with Chef 12, and this is not pinned in the openssh cookbook.

### ISSUE THREAD

**Issue by stefanwb** [chef-cookbooks/openssh#126]
### Cookbook version
2.8.1
### Chef-client version
12.21.31
### Platform Details
platform=centos
platform_version=7.7.1908

### Scenario:
Converging on Chef 12

The iptables cookbook bump to 7.0.0 breaks compat with Chef 12, and this is not pinned in the openssh cookbook.

Proposed fix (while we're all upgrading are chef clients hopefully): is to contstrain pessimistically like `iptables ~> 6.0` and release a new version of the openssh cookbook.

Thanks!

**Comment by tas50** [comment]
Chef versions less than 14 are no longer supported releases. We maintain compatibility in cookbooks like this where we can, but pinning a cookbook dependency like that would negatively impact users that are running currently supported version of Chef Infra Client. You really want to upgrade that Chef release. It's gotten a lot better in the last 4 years.

**Comment by stefanwb** [comment]
Tnx for your quick reply, Tim. I appreciate the reasoning but at least the metadata needs updating since it's has `chef_version '>= 12.15'` currently.

**Comment by tas50** [comment]
This particular cookbook does work with Chef 12.15 though. The user just needs to control their other dependencies, which is somewhat outside the scope of this cookbook since we don't have the ability to constrain to different cookbook versions based on the Chef Infra Client version.
