### ISSUE TITLE
Incorrect ordering of Port and ListenAddress options

### ISSUE THREAD

**Issue by GertBurger** [chef-cookbooks/openssh#44]
Openssh requires that certain options are present before others.

As per 'man sshd_config':
>If port is not specified, sshd will listen on the address and all prior Port options specified.  The default is >to listen on all local addresses.  Multiple ListenAddress
>             options are permitted.  Additionally, any Port options must precede this option for non-port >qualified addresses.

The incorrect ordering may result in ssh not starting if you specify the port using the Port option instead if of placing the port inside the ListenAddress.

**Comment by tas50** [comment]
#34 was cherry picked in and is part of the 1.6.0 release.
