### ISSUE TITLE
host_key_* attributes make incorrect configuration parameters

### ISSUE THREAD

**Issue by polew** [chef-cookbooks/openssh#54]
According to sshd_config manual there is only one configuration parameter HostKey. In attribute file there are few host_key_\* key-value pairs which produce parameters such as HostKeyRsa whitch are incorect. 
It is better to use array with any needen values eg.:

default['openssh']['server']['host_key'] = ['/etc/ssh/ssh_host_rsa_key', '/etc/ssh/ssh_host_dsa_key', '/etc/ssh/ssh_host_ecdsa_key', '/etc/ssh/ssh_host_ed25519_key']

The relevant portion of the manual:
HostKey
Specifies a file containing a private host key used by SSH.  The default is /etc/ssh/ssh_host_key for protocol version 1, and /etc/ssh/ssh_host_dsa_key, /etc/ssh/ssh_host_ecdsa_key, /etc/ssh/ssh_host_ed25519_key and /etc/ssh/ssh_host_rsa_key for protocol version 2.  Note that sshd(8) will refuse to use a file if it is group/world-accessible.  It is possible to have multiple host key files.  “rsa1” keys are used for version 1 and “dsa”, “ecdsa”, “ed25519” or “rsa” are used for ver‐sion 2 of the SSH protocol.  It is also possible to specify public host key files instead.  In this case operations on the private key will be delegated to an ssh-agent(1).

**Comment by treuss** [comment]
I second @polew  - this issue still exists.

**Comment by florian-asche** [comment]
Centos6 is missing. It should be:
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_dsa_key

**Comment by florian-asche** [comment]
You should also have a look here: https://github.com/BetterCrypto/Applied-Crypto-Hardening/blob/master/src/configuration/SSH/OpenSSH/6.6/sshd_config

**Comment by lucymhdavies** [comment]
We had an incident today, caused by 34887f9e0d0a53ef683213c3e5e2a72d222b8718 (released 3 days ago in v2.4.0), for RHEL 6.

As with CentOS 6, the keys are stored under `/etc/ssh`

I'll raise a PR to switch this over to /etc/ssh/

**Comment by tas50** [comment]
Looks like we have this fixed at this point
