### ISSUE TITLE
Default values for HostKey not suitable for CentOS 7

### ISSUE THREAD

**Issue by kkeane** [chef-cookbooks/openssh#61]
By default, this cookbook sets up no HostKey entries in sshd_config. sshd will then default to using the rsa and dsa key. However, CentOS 7 does not create a DSA key, causing an error message.

To avoid that, CentOS 7 should have explicit HostKey entries, as follows:

HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

**Comment by boldandbusted** [comment]
:+1: Seems like a dealbreaker for RHEL-family 7+.
