### ISSUE TITLE
Ciphers and MACs can't be set for server

### ISSUE THREAD

**Issue by ahrenstein** [chef-cookbooks/openssh#67]
In order to resolve Nessus alerts, we need to set Ciphers and MACs in sshd_config but the only option is to set them in ssh_config.

These are two settings that are missing from the cookbook.

**Comment by trilitheus** [comment]
Hey there, you can add any settings you need using attributes.  You should set them as ```snake_case ```and they will be rendered as ```CamelCase```.
For the settings you require you should set the node attributes:

    node['openssh']['server']['ciphers'] = 'aes256-ctr,aes192-ctr,aes128-ctr'
    node['openssh']['server']['m_a_cs'] = 'hmac-sha2-512,hmac-sha2-256'

note that these are examples and you should ensure you set these to appropriate settings for your needs.

**Comment by ahrenstein** [comment]
Ah I didn't know the cookbook can handle attributes that aren't explicitly defined. Thanks!
