### ISSUE TITLE
Error when using Ubuntu 15.04 with upstart

### ISSUE THREAD

**Issue by fletchowns** [chef-cookbooks/openssh#68]
Ubuntu 15.04 with systemd is supported per https://github.com/chef-cookbooks/openssh/pull/62 but I had to [switch back to upstart](https://wiki.ubuntu.com/SystemdForUpstartUsers#Permanent_switch_back_to_upstart) for a [different cookbook](https://github.com/xhost-cookbooks/system/issues/30) and now I'm running into an issue with the openssh cookbook:

```
[htpc] out: ---- Begin output of /bin/systemctl start ssh ----
[htpc] out: STDOUT:
[htpc] out: STDERR: Failed to get D-Bus connection: Operation not permitted
[htpc] out: ---- End output of /bin/systemctl start ssh ----
[htpc] out: Ran /bin/systemctl start ssh returned 1
[htpc] out: [2015-10-16T06:26:27+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
Any way to support both systemd & upstart for Ubuntu 15.04 in this cookbook?

**Comment by fletchowns** [comment]
In general, how come cookbooks have to be concerned about specifying service provider anyways?

**Comment by tas50** [comment]
Getting the correct service provider is tricky business since some distros (like ubuntu) are in a mixed state with both upstart/init or systemd/init.  I'll see if I can get a fix for Ubuntu 15.04 in the near future here.  It just requires a special case for newer Ubuntu releases.

**Comment by fletchowns** [comment]
@tas50 but how come every single cookbook has to handle that? Shouldn't that detection be built into the [service resource](https://docs.chef.io/resource_service.html) itself?

**Comment by tas50** [comment]
@fletchowns What version of chef-client were you running when you had this issue?  Chef 12 should just do the right thing.

**Comment by tas50** [comment]
@fletchowns I've tested on 15.04 using the latest release of the cookbook with Chef 12.6 and this doesn't seem to be an issue.  There have been changes to both the cookbook and to chef-client to better handle multiple init systems.  I'm going to close this out at this point.

**Comment by fletchowns** [comment]
Thanks @tas50 ! This was on Chef 11. I'm upgrading to Chef 12 this week, I'll give it another shot after that.
