### ISSUE TITLE
Add version lock on iptables dependency

### ISSUE THREAD

**Issue by jhsubscribe** [chef-cookbooks/openssh#71]
This cookbook depends on iptables but doesn't have a pessimistic version lock to ~ 1.0

Therefore when iptables introduced a breaking change and bumped to 2.0, this cookbook tries to use it  and errors.   This may only affect us because we're on Chef 11 but I still think it's best practice to have the version lock in place so that breaking changes are brought in intentionally.

If you want to change:
-depends 'iptables'
+depends 'iptables', "~> 1.0"

**Comment by tas50** [comment]
I made this same change.  I'll make a release soon.  FYI though this cookbook will be requiring the latest iptables release and Chef 12+ in the near future.

**Comment by jhsubscribe** [comment]
ok thanks
