### ISSUE TITLE
UseRoaming not valid in OpenSSH <5.4

### ISSUE THREAD

**Issue by tbunnyman** [chef-cookbooks/openssh#77]
On older boxes, like Cent 5.11, this breaks the ssh client on the box since it is an unrecognized config entry.

**Comment by bcg62** [comment]
+1 - its also breaking me on centos 6

OpenSSH_4.3p2, OpenSSL 0.9.8e-fips-rhel5 01 Jul 2008

Its available in 7.1p2
http://www.openssh.com/txt/release-7.1p2

For now in my wrapper i have the following as a work around.

if node['platform_version'].to_i < 7
  default['openssh']['client'].delete('use_roaming')
end

**Comment by dtoubelis** [comment]
+1 Breaks Centos 5.x

**Comment by tas50** [comment]
This has been fixed in the 2.0 release
