### ISSUE TITLE
Breaks sftp on RHEL 6

### ISSUE THREAD

**Issue by nkadel-skyhook** [chef-cookbooks/openssh#78]
The sshd_config on RHEL 6 fails to set SFTP access correctly. The difficulty is this line, which is published in the default openssh-server based sshd_config, but is not published by the default cookbook setting:

* Subsystem sftp /usr/libexec/openssh/sftp-server.

**Comment by tas50** [comment]
We're avoided setting config values on purpose.  If you look at the attributes file you can see al the attributes that you can use to tune the config.  You'll want to set this attribute in either a role/environment file or in a wrapper cookbook.

**Comment by nkadel-skyhook** [comment]
Can we re-open this? Forcing administrators to track CentOS releases themselves and hand-tune configurations to activate a tool for default use is precisely  the kind of setting that the upstream cookbooks should be able to provide correctly. I'll be happy to provide a patch, if needed.
