### ISSUE TITLE
Ubuntu 15.10

### ISSUE THREAD

**Issue by florian-asche** [chef-cookbooks/openssh#83]
Hi there,
i tested your cookbook on a Ubuntu 15.10 Server. Its working, but there are many things removed. I think this should not be the way for production.

For example logging or UsePrivilegeSeparation, are things that should not removed by default.

I think seperate each distribution and maybe version (attributes) is a way to go for a better cookbook. Chef-solo / local or chef-zero is build on a ssh connection and from that case it should be a perfect build cookbook like apache2.

Chef Team, please invest some time here!

>   * template[/etc/ssh/ssh_config] action create
>     - update content in file /etc/ssh/ssh_config from 6005ad to 738d96
>     --- /etc/ssh/ssh_config	2015-04-09 09:48:17.000000000 +0000
>     +++ /etc/ssh/.chef-ssh_config20160411-7179-1qindz9	2016-04-11 21:19:57.978480519 +0000
>     @@ -1,55 +1,6 @@
>     +# This file was generated by Chef for domoticz
>     +# Do NOT modify this file by hand!
>      
>     -# This is the ssh client system-wide configuration file.  See
>     -# ssh_config(5) for more information.  This file provides defaults for
>     -# users, and the values can be changed in per-user configuration files
>     -# or on the command line.
>     -
>     -# Configuration data is parsed as follows:
>     -#  1. command line options
>     -#  2. user-specific file
>     -#  3. system-wide file
>     -# Any configuration value is only changed the first time it is set.
>     -# Thus, host-specific definitions should be at the beginning of the
>     -# configuration file, and defaults at the end.
>     -
>     -# Site-wide defaults for some commonly used options.  For a comprehensive
>     -# list of available options, their meanings and defaults, please see the
>     -# ssh_config(5) man page.
>     -
>      Host *
>     -#   ForwardAgent no
>     -#   ForwardX11 no
>     -#   ForwardX11Trusted yes
>     -#   RhostsRSAAuthentication no
>     -#   RSAAuthentication yes
>     -#   PasswordAuthentication yes
>     -#   HostbasedAuthentication no
>     -#   GSSAPIAuthentication no
>     -#   GSSAPIDelegateCredentials no
>     -#   GSSAPIKeyExchange no
>     -#   GSSAPITrustDNS no
>     -#   BatchMode no
>     -#   CheckHostIP yes
>     -#   AddressFamily any
>     -#   ConnectTimeout 0
>     -#   StrictHostKeyChecking ask
>     -#   IdentityFile ~/.ssh/identity
>     -#   IdentityFile ~/.ssh/id_rsa
>     -#   IdentityFile ~/.ssh/id_dsa
>     -#   Port 22
>     -#   Protocol 2,1
>     -#   Cipher 3des
>     -#   Ciphers aes128-ctr,aes192-ctr,aes256-ctr,arcfour256,arcfour128,aes128-cbc,3des-cbc
>     -#   MACs hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160
>     -#   EscapeChar ~
>     -#   Tunnel no
>     -#   TunnelDevice any:any
>     -#   PermitLocalCommand no
>     -#   VisualHostKey no
>     -#   ProxyCommand ssh -q -W %h:%p gateway.example.com
>     -#   RekeyLimit 1G 1h
>     -    SendEnv LANG LC_*
>     -    HashKnownHosts yes
>     -    GSSAPIAuthentication yes
>     -    GSSAPIDelegateCredentials no
>     +UseRoaming no
>   * template[/etc/ssh/sshd_config] action create
>     - update content in file /etc/ssh/sshd_config from 70157d to bfb1d0
>     --- /etc/ssh/sshd_config	2016-03-20 21:17:14.298343064 +0000
>     +++ /etc/ssh/.chef-sshd_config20160411-7179-p7xacl	2016-04-11 21:19:58.010480303 +0000
>     @@ -1,89 +1,8 @@
>     -# Package generated configuration file
>     -# See the sshd_config(5) manpage for details
>     +# This file was generated by Chef for domoticz
>     +# Do NOT modify this file by hand!
>      
>     -# What ports, IPs and protocols we listen for
>     -Port 22
>     -# Use these options to restrict which interfaces/protocols sshd will bind to
>     -#ListenAddress ::
>     -#ListenAddress 0.0.0.0
>     -Protocol 2
>     -# HostKeys for protocol version 2
>     -HostKey /etc/ssh/ssh_host_rsa_key
>     -HostKey /etc/ssh/ssh_host_dsa_key
>     -HostKey /etc/ssh/ssh_host_ecdsa_key
>     -HostKey /etc/ssh/ssh_host_ed25519_key
>     -#Privilege Separation is turned on for security
>     -UsePrivilegeSeparation yes
>     -
>     -# Lifetime and size of ephemeral version 1 server key
>     -KeyRegenerationInterval 3600
>     -ServerKeyBits 1024
>     -
>     -# Logging
>     -SyslogFacility AUTH
>     -LogLevel INFO
>     -
>     -# Authentication:
>     -LoginGraceTime 120
>     -PermitRootLogin yes 
>     -StrictModes yes
>     -
>     -RSAAuthentication yes
>     -PubkeyAuthentication yes
>     -#AuthorizedKeysFile	%h/.ssh/authorized_keys
>     -
>     -# Don't read the user's ~/.rhosts and ~/.shosts files
>     -IgnoreRhosts yes
>     -# For this to work you will also need host keys in /etc/ssh_known_hosts
>     -RhostsRSAAuthentication no
>     -# similar for protocol version 2
>     -HostbasedAuthentication no
>     -# Uncomment if you don't trust ~/.ssh/known_hosts for RhostsRSAAuthentication
>     -#IgnoreUserKnownHosts yes
>     -
>     -# To enable empty passwords, change to yes (NOT RECOMMENDED)
>     -PermitEmptyPasswords no
>     -
>     -# Change to yes to enable challenge-response passwords (beware issues with
>     -# some PAM modules and threads)
>      ChallengeResponseAuthentication no
>     -
>     -# Change to no to disable tunnelled clear text passwords
>     -#PasswordAuthentication yes
>     -
>     -# Kerberos options
>     -#KerberosAuthentication no
>     -#KerberosGetAFSToken no
>     -#KerberosOrLocalPasswd yes
>     -#KerberosTicketCleanup yes
>     -
>     -# GSSAPI options
>     -#GSSAPIAuthentication no
>     -#GSSAPICleanupCredentials yes
>     -
>     -X11Forwarding yes
>     -X11DisplayOffset 10
>     -PrintMotd no
>     -PrintLastLog yes
>     -TCPKeepAlive yes
>     -#UseLogin no
>     -
>     -#MaxStartups 10:30:60
>     -#Banner /etc/issue.net
>     -
>     -# Allow client to pass locale environment variables
>     -AcceptEnv LANG LC_*
>     -
>     -Subsystem sftp /usr/lib/openssh/sftp-server
>     -
>     -# Set this to 'yes' to enable PAM authentication, account processing,
>     -# and session processing. If this is enabled, PAM authentication will
>     -# be allowed through the ChallengeResponseAuthentication and
>     -# PasswordAuthentication.  Depending on your PAM configuration,
>     -# PAM authentication via ChallengeResponseAuthentication may bypass
>     -# the setting of "PermitRootLogin without-password".
>     -# If you just want the PAM account and session checks to run without
>     -# PAM authentication, then enable this but set PasswordAuthentication
>     -# and ChallengeResponseAuthentication to 'no'.
>     +PasswordAuthentication no
>      UsePAM yes
>     +
>

**Comment by iennae** [comment]
@florian-asche thanks for investing the time to report this issue. Can you give some more information about the documentation you are including in here? the - headers with the information below? Are you suggesting that those should be the default options? Thanks!

**Comment by iennae** [comment]
@florian-asche Please do reopen when you have time to update the request for more information.
