### ISSUE TITLE
Addition of Ciphers option in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by sandeephello** [chef-cookbooks/openssh#88]
### Cookbook version

v1.3.4
### Chef-client version

12.11.18
### Platform Details

Amazon Linux
### Scenario:

In /etc/ssh/sshd_config, there is a option to configure Ciphers

http://linux.die.net/man/5/sshd_config

Ciphers aes128-ctr aes192-ctr aes256-ctr

but there is not attribute in this cookbook to configure ciphers. 
### Actual Result:

Please consider this request as feature request.

**Comment by robertlabrie** [comment]
You can set any attribute like this:
`default['openssh']['server']['ciphers'] = 'aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-cbc'`

*BUT* the sample in the cookbook 
`default['openssh']['client']['ciphers'] = [ 'aes128-ctr aes192-ctr aes256-ctr arcfour256 arcfour128 aes128-cbc 3des-cbc' ]
`
generates an invalid sshd_config. The ciphers need to be comma separated.

**Comment by tas50** [comment]
Fix is above
