### ISSUE TITLE
sftp not working withe openssh v2.1.0 (for rhel)

### ISSUE THREAD

**Issue by jaininshah9** [chef-cookbooks/openssh#90]
### Cookbook version

2.1.0
### Chef-client version

12.5.1
### Platform Details

CentOS/RHEL 5,6,7
### Scenario:

using sftp to connect to the server
### Steps to Reproduce:

Nothing special, just run openssh cookbook and sftp does not work on CentOS/RHEL 5,6,7
### Expected Result:

$ sftp -oPort=2201 vagrant@127.0.0.1:
vagrant@127.0.0.1's password: 
Connected to 127.0.0.1.
Changing to: /home/vagrant/
### Actual Result:

$ sftp -oPort=2201 vagrant@127.0.0.1:
vagrant@127.0.0.1's password: 
subsystem request failed on channel 0
Couldn't read packet: Connection reset by peer

Logs present in the file : /var/log/secure.
Oct 10 15:45:46 127.0.0.1 sshd[23659]: subsystem request for sftp
Oct 10 15:45:46 127.0.0.1 sshd[23659]: error: subsystem: cannot stat /usr/lib/openssh/sftp-server: No such file or directory
### How to Fix:

replace this 

```
default['openssh']['server']['subsystem'] = 'sftp /usr/lib/openssh/sftp-server' if platform_family?('rhel') || platform_family?('fedora')
```

with

```
default['openssh']['server']['subsystem'] = 'sftp /usr/libexec/openssh/sftp-server' if platform_family?('rhel')
default['openssh']['server']['subsystem'] = 'sftp /usr/lib/openssh/sftp-server' if platform_family?('fedora')
```

**Comment by jaininshah9** [comment]
I can create a PR if you would like and push the changes.

**Comment by nkadel-skyhook** [comment]
Thanks for the hint, I just created a pull request. it's a 2 line request, so hopefully it can be taken while I sign forms for my new email address.

   https://github.com/chef-cookbooks/openssh/pull/93

**Comment by chewi** [comment]
@jaininshah9 already created #91.

**Comment by tas50** [comment]
I'll get this shipped asap
